name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
    - run: export GIN_MODE=release
    - run: go test -v ./...
